const express = require("express")
const { JsonWebTokenError } = require("jsonwebtoken")
const  mongoose = require('mongoose')
const mongoconnection = ("mongodb://localhost:/students")
const app = express()
mongoose.connect(mongoconnection, {useNewUrlParser:true, useUnifiedTopology: true })
const conn = mongoose.connection;
conn.on("open",()=>{
    console.log("connection is working ")
})
const router = require("./controllers/userLogin")
app.use(express.json())
app.use("/",router)
require('./controllers/userLogin')
app.use(express.json())
app.listen(4000,()=>console.log(`server is running on port ${4000}`))